### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by Kempe** [steamcore/TinyIpc#1]
Hi David,
after building your TinyIPC Project without errors and warnings, I run your sample project.... but it did not work as expected... sending seems to work (MessageSent property is increasing for each sent message), but the sample did not receive anything... Can you help me out?
Cheers,
Micha

**Comment by DavidZidar** [comment]
Thanks for the bug report, as you noticed there is a bug in the example project. The message bus ignores it's own messages by design, the example code should be using two separate instances of MessageBus to simulate separate processes. I will fix the example soon.

**Comment by DavidZidar** [comment]
Hi, I finally had time to have a look so I added a bunch of unit tests and fixed the issue. The example should work fine now.
