### ISSUE TITLE
Randomly getting this 

### ISSUE THREAD

**Issue by SpuriousSnail86** [steamcore/TinyIpc#10]
System.TimeoutException: Gave up waiting for read lock
   at TinyIpc.Synchronization.TinyReadWriteLock.AcquireReadLock()
   at TinyIpc.IO.TinyMemoryMappedFile.Read()
   at TinyIpc.Messaging.TinyMessageBus..ctor(ITinyMemoryMappedFile memoryMappedFile, Boolean disposeFile, TimeSpan minMessageAge)

when calling the constructor, presumably to create the memory mapped file

any idea how to fix. The only way it goes away is if i restart my machine

**Comment by DavidZidar** [comment]
That probably means you still have some process that's stuck holding the locks, once all processes running TinyIpc shuts down everything is automatically deleted by Windows so you really should not need to restart Windows. Check task manager and make sure you clean up properly with a try/finally or a using statement.

**Comment by SpuriousSnail86** [comment]
how can you stop this happening. because it happens randomly.

how can you force the locks to be freed?

**Comment by DavidZidar** [comment]
I'm not sure, I have not had this issue. If you are properly disposing everything this shouldn't happen. There could be a bug of course, but I can't even begin to investigate if I can't reproduce it. Can you make a repo that reproduces this somewhat reliably?

**Comment by SpuriousSnail86** [comment]
its very hard to reproduce. because its totally random. i am disposing everything by calling Dispose on the TinyMessageBus but even then it doesnt help

**Comment by SpuriousSnail86** [comment]
it definitely appears to be a bug. as it just happens totally randomly

**Comment by SpuriousSnail86** [comment]
the only way to fix is to terminate the other processes (that access the memory mapped file)

**Comment by DavidZidar** [comment]
Can you describe your use case? It would be helpful to understand how this might be happening. Like, do you have a couple of long running processes or lots of processes joining in and dropping out? Does it happen soon after the locks, file, and messagebus are created or hours or days later?

**Comment by SpuriousSnail86** [comment]
It's completely random. but generally I have a master process and client processes . Both the client and master processes instantiate an instance of the TinyMessageBus, attach the Received event handler and send messages to each other with PublishAsync. When reloading the child processes, dispose gets called on the client processes. I will double check the master process also disposes. This could be the problem

**Comment by DavidZidar** [comment]
@SpuriousSnail86 Hi, I've spent the last couple of weekends working on TinyIpc and have now released version 4.0.0 which does have a few breaking changes but they're all meant to improve TinyIpc in various ways. I spent a lot of time trying to make the locking mechanism more robust so I'm hoping this release will resolve your problem even though I haven't exactly been able to reproduce it.

**Comment by DavidZidar** [comment]
I'm closing this issue due to lack of responses, but I'm hoping it works fine now.
