### ISSUE TITLE
Receiving messages too slowly

### ISSUE THREAD

**Issue by MuNet** [steamcore/TinyIpc#12]
If the message content is long, the receiving of the message will be very slow, and the interval can even reach 2-3 seconds.
Any good suggestions? 
Version is 3.11

**Comment by DavidZidar** [comment]
Hi,

1. Read the README-file, TinyIpc is not meant for long messages because of how it works
2. Try the newest version, it's faster
3. 2-3 seconds sounds extremely long, how large are the messages?

**Comment by MuNet** [comment]
> 你好
> 
> 1. 阅读自述文件，TinyIpc 不适用于长消息，因为它的工作原理
> 2. 尝试最新版本，速度更快
> 3. 2-3秒听起来很长，消息有多大？

I tinkered with the code containing the delay in the source code and it worked miraculously, thank you so much for providing such an excellent solution

**Comment by DavidZidar** [comment]
Glad you like it! So I guess there's no problem then? I'm closing this issue.
