### ISSUE TITLE
Named Semaphore not supported on Unix platforms

### ISSUE THREAD

**Issue by AlexHarper** [steamcore/TinyIpc#5]
This is the issue documenting the problem with a lot of the named primitives:
https://github.com/dotnet/coreclr/issues/1237
Basically I don't think this will work under any platforms other than Windows.

I put together a version of the library without the semaphores to control the maximum number of readers/clients but I have only had a very cursory read through the code base so I don't know if that's a terrible idea or not?

**Comment by DavidZidar** [comment]
Oh, that's bad, I didn't know that. I've only used this library on Windows myself.

The class `TinyReadWriteLock` is the central locking mechanism in the repo and it allows several readers at once but when taking a write lock it also takes all the read locks to ensure that no one is reading while the data is being manipulated. For example, while writing new messages to the memory mapped file the file is often completely rewritten to remove old messages.

Removing the semaphores is not a good idea, it would probably lead to all kinds of problems. Imagine two processes writing at the same time or if one process is reading while another rewrites the entire file, it wouldn't be pretty.

Maybe one could implement semaphore like functionality on top of the file itself, I'd have to think more about that though.

**Comment by zhuyinheng** [comment]
i think named semaphore primitive has been added into mono and core-clr. refers to #5030 @AlexHarper

**Comment by guilhermecaixeta** [comment]
I've get the same error when I tried to execute CI in Linux or MacOs.

**Comment by DavidZidar** [comment]
I'm closing this old issue, I updated the README-file with OS info a year ago.
