### ISSUE TITLE
Global Memory Map Issue

### ISSUE THREAD

**Issue by mkreuzmayr** [steamcore/TinyIpc#7]
I am using this Library for a very long time now, and the thing that is missing imo is the ability to create globally mapped files. So i could communicate between Services and Processes. This could be acomplished by maybe adding a flag, that prepends the "Global\" prefix to all Handles.

**Comment by DavidZidar** [comment]
A bit late with this response, but all primitives are configurable, see this unit test as a reference:
https://github.com/steamcore/TinyIpc/blob/0a42e1cb5edbaccff17a9f84ca936548f8b9877b/src/TinyIpc/Messaging/TinyMessageBus.Tests.cs#L76-L97
